[project]
name = "acolite-mp"
version = "0.1.0"
description = "Acolite modified to run with multiple cores"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyresample",
    "cartopy",
    "scipy",
    "numpy",
    "pyhdf",
    "gdal==3.12.3",
    "netcdf4",
    "h5py",
    "pygrib",
    "requests",
    "matplotlib",
    "scikit-image",
    "pyproj",
    "pyinterp",
]

[project.optional-dependencies]
test = [
    "matplotlib>=3.10.3",
    "memory-profiler>=0.61.0",
    "pytest>=8.3.5",
    "xarray>=2025.4.0",
]

[tool.uv]
no-binary-package = ["gdal"]